#!/bin/zsh# arch切り替えのためにzshrcで処理する
# Kiro CLI pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zprofile.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zprofile.pre.zsh"
# # uname -m コマンドを使ってマシンのアーキテクチャを取得
# arch=$(uname -m)
# 
# # アーキテクチャが "arm64" なら M1以降のMac
# if [ "$arch" = "arm64" ]; then
#     eval $(/opt/homebrew/bin/brew shellenv)
# fi

# Kiro CLI post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zprofile.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zprofile.post.zsh"
