# operate windows settings
set -s escape-time 0
set -g renumber-windows on
bind -n M-n new-window -c "#{pane_current_path}"
bind -n M-l next-window
bind -n M-h previous-window
bind -n M-r command-prompt "rename-window -- '%%'"

bind -n M-N command-prompt "new-session -n '%1'"
bind -n M-j switch-client -n
bind -n M-k switch-client -p

# split window settings
bind -n M-/ split-window -h -c "#{pane_current_path}" # Conflict vim to setting Ctrl
bind -n M-- split-window -v -c "#{pane_current_path}"
